// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0kiBl8ocxFhUv42y1e-EU06aP1cVlPyU',
    appId: '1:68163902008:web:00b20a8e6136dca3c424cd',
    messagingSenderId: '68163902008',
    projectId: 'enxovalbaby-d4846',
    authDomain: 'enxovalbaby-d4846.firebaseapp.com',
    storageBucket: 'enxovalbaby-d4846.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgeDw24OW_ddHCmwFrR_NZ1yZToVj4Os0',
    appId: '1:68163902008:android:1f5c700286f5e40ac424cd',
    messagingSenderId: '68163902008',
    projectId: 'enxovalbaby-d4846',
    storageBucket: 'enxovalbaby-d4846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_6BH6-5iniRNM2NaObiCJ4E7i8OBXvM',
    appId: '1:68163902008:ios:6595b634d4a27b33c424cd',
    messagingSenderId: '68163902008',
    projectId: 'enxovalbaby-d4846',
    storageBucket: 'enxovalbaby-d4846.firebasestorage.app',
    iosBundleId: 'com.example.enxovalBaby',
  );

}