name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Rodar flutter pub get
        run: flutter pub get

      - name: Rodar testes
        run: flutter test

      - name: Gerar APK de debug
        run: flutter build apk --debug
